### ISSUE TITLE
Not able to pair with Zwift om computer

### ISSUE THREAD

**Issue by beer-rich** [lefty01/ESP32_TTGO_FTMS#19]
Hi. I have used this with The Zwift Companion app on my phone successfully. But I am unable to get my computer to show the esp threadmill ingame. I have confirmed the PC has BLE and that ut is able to see the ESP in the "add bluetooth device wizard". Having ut on the computer would make it a lot easier to use for multiple users. Any help is appreciated.

**Comment by lefty01** [comment]
Hi ... not sure if I can help. But how is you setting in the Zwift app on your PC (is it windows PC?)?
you can choose connect via built-in bluetooth or connect via Zwift companion.
On windows PC zwift I use the setting "built-in bluetooth" that works for me. I would think it is even a bit more "stable" connection then with my android phone.

have you played with these two options within zwift?  IIRC I did not pair the ESP with windows (like adding a bt device or something ... so maybe  you can try unpari from PC again then start Zwift and try use built-in bluetooth?? )

**Comment by beer-rich** [comment]
Thanks for the quick reply and confirming this should work.

Yeah, its set to built in - I can pair with Heart Rate BLE Strap for instance.

I tried playing with unpairing/paring etc., but no difference.

Probably something with my computer then atleast. 
Do you see the same BLE capabilites on your bluetooth device on your computer that is working?

![image](https://user-images.githubusercontent.com/84505578/153396401-fae17074-7dd5-43d3-9a33-5b0dcb5b16f0.png)
![image](https://user-images.githubusercontent.com/84505578/153396459-a0dc5946-4dce-416c-8a79-41eb0466d8c8.png)
![image](https://user-images.githubusercontent.com/84505578/153396495-1a7df7f6-e190-4b99-800a-916ad35e4c4c.png)

**Comment by lefty01** [comment]
as far as I can see this looks same here.

**Comment by lefty01** [comment]
any success? any chance to try another PC and/or ESP board? not sure if you could enable some ESP Core debug function that could help debug the connection issue. or maybe some debug  prints  within the bluetooth code?
one other thing that came to my mind since I was wondering if we could cleanup the bluetooth and stick with only the "NimBLE" stack ... at this point you might be able to undefine NIMBLE in the code an run with the BLEDevice instead of NimBLEDevice ... although I doubt that it would make a difference

**Comment by beer-rich** [comment]
Finally got to try with another ESP board and I have no issues now. Closing the issue.

**Comment by lefty01** [comment]
cool thx for the update
