### ISSUE TITLE
more thanone instance of overloaded function "TwoWire::begin matches the argument list 

### ISSUE THREAD

**Issue by smitec11** [lefty01/ESP32_TTGO_FTMS#25]
in ESP32_TTGO_FTMS.cpp line 1101:

I2C_0.begin(SDA_0 , SCL_0 , I2C_FREQ);

will give error when building.

should be :

I2C_0.begin(SDA_0 , SCL_0 , (uint32_t) I2C_FREQ);

**Comment by zingo** [comment]
Thanks for reporting!
I made this on my fork 
https://github.com/zingo/ESP32_TTGO_FTMS/commit/6f0deaaba267e80c204e0c5f4158d71cfe72a7b8
a while ago I think it will solve this for you.

I created this pull request for this repo
https://github.com/lefty01/ESP32_TTGO_FTMS/pull/26

**Comment by smitec11** [comment]
welcome.

can you contact me on the pm I send you? regards, Chris

**Comment by zingo** [comment]
No problem but I can't find it but I also have not used PM in github before :)
Is the one in gitter from 22 Aug?
https://gitter.im/lefty01/ESP32_TTGO_FTMS?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications

**Comment by lefty01** [comment]
merged #26
@zingo also note this commit: https://github.com/lefty01/ESP32_TTGO_FTMS/commit/cd9e4a1a89b27e7d2adb48c9d349f63fd03d7649
fixes the same issue for tagert ttgo-T4

**Comment by smitec11** [comment]
@zingo,  I used gitter for the PM.
